### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by Xsmael** [pkrumins/node-iptables#2]
Hello, i just tried, the example given on the readme, but it doesnt change anything in the iptables

here is the code:
```

 var iptables = require('iptables');

    iptables.allow({
        protocol : tcp,
        src : '10.1.1.5',
        dport : 34567,
        sudo : true
    });

    iptables.drop({
        protocol : 'tcp',
        dport : 34567,
        sudo : true
    });
```

**Comment by soonsebii** [comment]
@Xsmael you meet error when run example code. Check this below code.

> ReferenceError: tcp is not defined

iptables.allow({
  protocol : 'tcp',
  ....
});

**Comment by Xsmael** [comment]
oh damn!, indeed, i don't know what i did before, my bad.... sorry, it works now
